version: '3.8'

services:

  db:
    image: postgres:16-alpine
    container_name: nl-postgres
    restart: always
    environment:
      POSTGRES_USER: nluser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: article_place
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  site:
    image: ryepenchi/nl_site:1.2
    container_name: nl-site
    restart: always
    env_file:
      - ".env"
    stop_signal: SIGINT
    ports:
      - 8080:8080
    depends_on:
      - "db"

  ingest:
    image: ryepenchi/nl_ingest:1.1
    container_name: nl-ingest
    env_file:
    - ".env"
    depends_on:
      - "db"
    profiles:
      - optional

volumes:
  pgdata:
