services:

  db:
    image: postgres:16-alpine
    container_name: ${POSTGRES_CONTAINER_NAME:-nl-postgres}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pg_nl_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-battery13horse67staple23}
      POSTGRES_DB: ${POSTGRES_DB:-pg_db_article}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      nl-network:

  site:
    image: ryepenchi/nl_site:1.3
    container_name: nl-site
    restart: always
    stop_signal: SIGINT
    environment:
      POSTGRES_CONTAINER_NAME: ${POSTGRES_CONTAINER_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      FLASK_DEBUG: ${FLASK_DEBUG:-false}
      ENVIRONMENT: ${ENVIRONMENT:-testing}
      MAPBOX_TOKEN: ${MAPBOX_TOKEN}
    ports:
      - "${NL_WEBPORT:-8080}:8080"
    depends_on:
      - "db"
    networks:
      nl-network:

  ingest:
    image: ryepenchi/nl_ingest:1.3
    container_name: nl-ingest
    environment:
      POSTGRES_CONTAINER_NAME: ${POSTGRES_CONTAINER_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - "db"
    profiles:
      - optional
    networks:
      nl-network:

volumes:
  pgdata:

networks:
  nl-network:
